### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [dcfemtech/dcfemtech_site_old#22]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://dcfemtech.github.io So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by leahbannon** [comment]
Done. Thanks!

**Comment by konklone** [comment]
And thank you!
